### ISSUE TITLE
Pasta .idea

### ISSUE THREAD

**Issue by abreuermelinda** [tuliorezende/VacinasOnline#1]
Boa tarde, Túlio. Sou colega de faculdade do Luís e integrante do projeto Vacinas Online. No sábado à noite eu baixei e abri o projeto e tava tudo ok. Porém hoje quando fui abri-lo novamente, acusou um erro nos arquivos misc e modules da pasta .idea. Então, apaguei  a pasta q estava salva em meu notebook e baixei o projeto novamente. Porém, quando fui abrir de novo no Android Studio o mesmo erro ocorreu. O que será que está acontecendo que está causando esse erro?

**Comment by tuliorezende** [comment]
Opa, tudo bom?

Então.....no início do projeto eu estava tendo prolema parecido, mas parecia ser por falta do gradle parece....apaga todos os arquivos .iml, que quando voce reabir o projeto ele vai gerar novamente.
